server:
  port: 9000
#  rabbitmq配置
spring:
  rabbitmq:
    username: admin
    password: admin
    virtual-host: /
    host: 192.168.92.130
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 2000
